#%RAML 1.0
title: BGP Info Api
mediaType: application/json
version: v0.1
baseUri: http://localhost:5000/v1

/vp_data/{RCs}:
    /{VPs}:
        /latest:
            get:
                description: Retrieve latest Information about given RCs and VPs
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "query": "v1/vp_data/get/rrc01,rrc02/all/latest",
                                    "time": {
                                        "from": 1531123200,
                                        "to": 1531123500
                                    },
                                    "data": {
                                        "rrc01": {
                                            "AS001": {
                                                "123.123.123.123": {
                                                    "valid": 12,
                                                    "unknown": 13,
                                                    "invalid": 42
                                                },
                                                "1.2.3.4": {
                                                    "valid": 11,
                                                    "unknown": 23,
                                                    "invalid": 54
                                                }
                                            },
                                            "AS002": {
                                                "123.123.123.123": {
                                                    "valid": 12,
                                                    "unknown": 13,
                                                    "invalid": 42
                                                },
                                                "1.2.3.4": {
                                                    "valid": 11,
                                                    "unknown": 23,
                                                    "invalid": 54
                                                }
                                            },
                                        },
                                        "rrc02": {
                                            "AS001": {
                                                "123.123.123.123": {
                                                    "valid": 3,
                                                    "unknown": 2,
                                                    "invalid": 123
                                                }
                                        }
                                    }
                                }

